# config.yaml 示例配置

# CSV 文件地址，可以是在线 URL 或本地路径
csv_url: "https://docs.google.com/spreadsheets/d/.../export?format=csv&gid=0"

# 最大并发数量
max_concurrent: 5

# 是否在首次 MISS 时下载完整文件触发缓存
download_if_miss: false

# 重试次数
retry_times: 2

# 下载后等待多久再进行 HEAD 检测 (秒)
head_wait_seconds: 1

# 检测哪些列的 URL
columns:
  - url
  - cover
  - lrc

# 是否保留下载的文件（默认删除）
keep_downloaded_file: false

# 下载文件的存放目录（仅当 keep_downloaded_file 为 true 时生效）
download_dir: "downloads"

# 输出结果文件名
output_csv: "output_cache_status.csv"

# -------------------------
# Cloudflare API 配置
# -------------------------
auto_purge_cf_cache: false # 是否开启自动清除 CF 缓存
# 清除单个 URL 缓存时使用
cf_api_url: "https://api.cloudflare.com/client/v4"  # 默认 API 地址
cf_api_token: "your_cf_api_token_here"             # 替换为实际 API Token
cf_zone_id: "your_cf_zone_id_here"                 # 替换为你的 Zone ID